# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b68a288c41ade6a0ef38eee3832398c7fac1520b6d6babcd8765f170041d10477b073e7fbfdde3ebb36e6145c00554e7affb23078e60c3c0bf8096cbf9504fec

test:
  secret_key_base: e87489d4e40c2530e84b2227d5ed993cc12a67434a444f5ac9490712c6f21acec6fce76137298aed038c67e52658a4e0ec03351028e4064ea895784bbd6d9228

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
